### ISSUE TITLE
Update tests to use testkit project

### ISSUE THREAD

**Issue by yg-apaza** [lagom/online-auction-java#124]
#121 was merged, next steps are related to updating the existing tests to use the new `testkit` project
Since all source code for `testkit` project was extracted from Item service, I only updated the dependencies in that service
- [x] Update tests in Transaction Service (#134)
- [x] Update tests in User Service (#139)
- [ ] Maybe we should add integration tests on Bidding Service?

**Comment by ignasi35** [comment]
tracking the open subtask on https://github.com/lagom/online-auction-java/issues/173
