### ISSUE TITLE
event store uniqueness , saga ,optimistic ui updates 

### ISSUE THREAD

**Issue by fortm** [lagom/online-auction-java#158]
Hi

Question is more around getting some pointers on using Lagom stack which is opinionated. Cassandra is where Lagom stores events on write-side. In addition, we can use cassandra and databases like elastic search on read side like this project. 

But, Cassandra is especially inefficient with "unique inserts", something that the Event Store relies on to guarantee no aggregates are concurrently accessed. So I was wondering how is that taken care of inside Lagom stack.

Secondly, where we commonly require ACID guarantees like amount deducted from one account and credited to another account, without adding any relational database into mix - do we have to rely on compensating events only ? But I have not found an implementation of saga pattern inside lagom.

Lastly, in User interfaces we use optimistic updates when Write operation is followed by optimistic update in UI. There after , Write request sends output of subsequent READ which is used to undo or keep the optimistic state when request completes. I have heard about task based UI but was not very clear about how to make these kinds of optimistic UI when write and read are decoupled like with Lagom.

Thanks

**Comment by ignasi35** [comment]
Hi @fortm this seems to be a generic question, not specific to this repository which may be of interest to other Lagom users. 

I think this is better asked in the [lagom mailing](https://groups.google.com/forum/#!forum/lagom-framework) list or the [gitter channel](https://gitter.im/lagom/lagom). 

I will close this issue hoping you can move the question there. Thanks!
