### ISSUE TITLE
Provide a Maven example

### ISSUE THREAD

**Issue by TimMoore** [lagom/online-auction-java#21]
We discussed converting this project to Maven as an example for Maven/Java users.

Our current thinking is to have both `build.sbt` and `pom.xml` files on the `master` branch, and then to also have long lived `sbt` and `maven` branches that strip the opposite build files out.

**Comment by lakhina** [comment]
I am working on this maven port. But having issue in replacing `enablePlugins(PlayJava && LagomPlay)` `enablePlugins(LagomJava)` 

Where can I find these plug-ins for maven?

**Comment by TimMoore** [comment]
@lakhina in Maven, there is just one `lagom-maven-plugin`, but it has different options for enabling Play and Lagom projects.

Probably the easiest way to see how to configure it is to create a new Maven project using the archetype to see how that's configured.

http://www.lagomframework.com/documentation/1.3.x/java/GettingStartedMaven.html

There are some more docs on Maven builds at http://www.lagomframework.com/documentation/1.3.x/java/LagomBuild.html

However, as someone pointed out on Gitter, Play does not yet have official support for Maven, so resolving this issue may require integrating another, third-party Maven plugin for Play.

**Comment by ignasi35** [comment]
There are other Lagom examples based in Maven:

 * https://github.com/lagom/lagom-java-maven-chirper-example
 * https://github.com/lagom/ibm-integration-examples
 * https://github.com/lagom/lagom-recipes

The ongoing efforts to make this project a hybrid sbt/mvn are abandoned. I'm closing this issue.
