### ISSUE TITLE
Remove Scala code

### ISSUE THREAD

**Issue by benmccann** [lagom/online-auction-java#22]
If this is really a Java example then we should not require Scala code. See https://github.com/lagom/online-auction-java/blob/master/web-gateway/src/main/java/controllers/package.scala

**Comment by benmccann** [comment]
I had to configure the project as a Scala project in Eclipse to get it to work. We should remove the workaround https://github.com/lagom/online-auction-java/pull/23 when this issue is fixes

**Comment by lakhina** [comment]
@jroper Should I replace the scala code?

**Comment by jroper** [comment]
I don't think it's possible to replace - you can't supply a package level implicit field constructor with Java since Java doesn't support implicits.

**Comment by lakhina** [comment]
@jroper Hello Sir, I got a doubt. Then how is this project a java if we are forced to use scala in middle.

**Comment by jroper** [comment]
The project also use JavaScript, HTML, CSS, XML, and a number of other languages.  The templating language used, twirl, is based on Scala.  The build file uses Scala.  It's very common for applications to use multiple languages, even if they primarily use one language.

**Comment by benmccann** [comment]
One difference is that Java and Scala are compiled together and the Java code doesn't work without the Scala code. That means you can't edit the Java code in your IDE without Scala support installed

I've never used Play's internationalization stuff before, so unfortunately I don't have any suggestions on other solutions for this.

**Comment by jroper** [comment]
That's actually not the case here - the Scala code is only used by the twirl templates. If we weren't using twirl templates, this code would not be needed. So Scala support is needed in the IDE because we're using twirl, not because of this Scala code.

**Comment by lakhina** [comment]
@jroper Thanks for info :)

So this issue should be closed?

**Comment by dwijnand** [comment]
I guess so.
