### ISSUE TITLE
Document that the Lombok plugin is needed to load the project in IntelliJ IDEA

### ISSUE THREAD

**Issue by TimMoore** [lagom/online-auction-java#28]
Currently the initial experience for someone importing this project into their IDE is to see errors.

The README should mention that they should install this plugin to make it import cleanly:

https://github.com/mplushnikov/lombok-intellij-plugin

**Comment by lakhina** [comment]
I wanted to know if Lombok plugin is also needed in case of eclipse?

**Comment by ignasi35** [comment]
@lakhina that is a very good question. Both IDEs require a plugin, please have a look at: http://www.lagomframework.com/documentation/1.3.x/java/Immutable.html#Lombok

Actually, we could x-ref this project's docs to Lagom documentation.
