### ISSUE TITLE
It's impossible to create an auction with a currency of Japanese Yen

### ISSUE THREAD

**Issue by jroper** [lagom/online-auction-java#30]
When you create an auction in Japanese Yen, it's impossible to enter a valid increment, if it's less than 50, you get an error of invalid.step, if it's more than 50, you get an error of invalid.increment.

**Comment by yg-apaza** [comment]
#37

**Comment by yg-apaza** [comment]
Fixes #37

**Comment by garg-anuj** [comment]
This issue is pending from long time. Should I work on it or should I let apaza finish this?
