### ISSUE TITLE
Routes collision in ConductR

### ISSUE THREAD

**Issue by ignasi35** [lagom/online-auction-java#32]
When deploying the application in ConductR it deems unusable due to a route collision.

The collision is for the route:

` POST /user`

that should only be resolved by `webGateway` as described in https://github.com/lagom/online-auction-java/blob/master/web-gateway/conf/routes#L6

but the default `bundle.conf` for `users-impl` is configuring the service as:

```cat ./user-impl/target/bundle/bundle/tmp/bundle.conf 
version              = "1"
name                 = "userimpl"
compatibilityVersion = "1"
system               = "userimpl"
systemVersion        = "1"
nrOfCpus             = 0.1
memory               = 402653184
diskSpace            = 200000000
roles                = ["web"]
components = {
  userimpl = {
    description      = "userImpl"
    file-system-type = "universal"
    start-command    = ["userimpl/bin/userimpl", "-J-Xms134217728", "-J-Xmx134217728", "-Dhttp.address=$USER_BIND_IP", "-Dhttp.port=$USER_BIND_PORT", "-Dplay.crypto.secret=75736572496d706c"]
    endpoints = {
      "user" = {
        bind-protocol = "http"
        bind-port     = 0
        services      = ["http://:9000/user"]  <-- I suspect this is the cause of the collision.
      },
      "akka-remote" = {
        bind-protocol = "tcp"
        bind-port     = 0
        services      = []
      }
    }
  }
}
```

*UPDATE*: similar collisions with `/item` and `/search`.

**Comment by markusjura** [comment]
Having a Lagom Descriptor called `user` and another service that is using the `/user` route is not possible.

Under ConductR, each Lagom service is accessible under `http://:9000/DESCRIPTOR_NAME` where `DESCRIPTOR_NAME` is the name of the Descriptor: https://github.com/lagom/online-auction-java/blob/master/user-api/src/main/java/com/example/auction/user/api/UserService.java#L25

This suffix is necessary so that every service can use the same port 9000.

So you either rename the Descriptor name of the `user-api` service or the route of `webGateway`.

**Comment by ignasi35** [comment]
> So you either rename the Descriptor name of the user-api service or ...

Exactly what I did. ;-)

**Comment by ignasi35** [comment]
Thanks for the detailed explanation!

**Comment by ignasi35** [comment]
@markusjura why is `http://:9000/user` even published in the service gateway if that's a private API? I would expect ` user -> [<list of (ip/port)] ` to exist in a Service Registry that's only consumable from the private network.

What is the motivation to expose the list of services in  `http://:9000/<service-name>` ?

**Comment by ignasi35** [comment]
Related to #17

**Comment by TimMoore** [comment]
Yeah, what does `http://:9000/user` even route to? Shouldn't only ACLs declared by the service descriptor be exposed?

**Comment by ignasi35** [comment]
>Yeah, what does http://:9000/user even route to? Shouldn't only ACLs declared by the service descriptor be exposed?

@markusjura  does this question still apply? If so, can we find some docs on the subject? /cc @TimMoore

**Comment by markusjura** [comment]
@ignasi35 Yes, it still applies. I would need to dive a bit deeper into that again to gain a full understanding. Will not be able to do that today. Hopefully, beginning of next week. I keep you posted.

**Comment by anii1234** [comment]
Run "cf unmap-route YOUR-APP-NAME OLD-ROUTE" to remove the existing route from that app.

**Comment by anii1234** [comment]
$ cf env my-app
 Getting env variables for app my-app in org My-Org / space development as admin...
 OK

 System-Provided:
 {
   "VCAP_SERVICES": {
     "p-mysql-n/a": [
       {
         "credentials": {
           "uri":"postgres://lrra:e6B-X@p-mysqlprovider.example.com:5432/lraa
         },
         "label": "p-mysql-n/a",
         "name": "p-mysql",
         "syslog_drain_url": "",
         "tags": ["postgres","postgresql","relational"]
       }
     ]
   }
 }

 User-Provided:
 my-env-var: 100
 my-drain: http://drain.example.com



//u can also review this example..

**Comment by TimMoore** [comment]
@anii1234 I think you might be in the wrong place 😄

**Comment by ignasi35** [comment]
This is solved. `user-service` no longer collisions with `web-gateway`
