### ISSUE TITLE
Upgrade to Lagom 1.3.0

### ISSUE THREAD

**Issue by ignasi35** [lagom/online-auction-java#34]
Lagom 1.3.0 introduces some features that should be showcased in online-auction-java:

 - `ProducerStub` for testing Broker consumption
 - replacing `service-name` and `acls` configurations with `bindServiceInfo`programmatic approach.

**Comment by lakhina** [comment]
@ignasi35 Please tell it is partially complete after https://github.com/lagom/online-auction-java/pull/35

**Comment by ignasi35** [comment]
Good catch @lakhina . This is almost ready and only `project/plugins.sbt` needs reviewing. Want to do the honours?

**Comment by lakhina** [comment]
@ignasi35  Sure :)
