### ISSUE TITLE
Project is not working properly with activator

### ISSUE THREAD

**Issue by lakhina** [lagom/online-auction-java#41]
This project is no longer properly working with `$ activator runAll` 
On gitter I got to know that lagom is gradually moving out of activator. I suggest we should remove activator and activator.bat

**Comment by lakhina** [comment]
Should I go for it?

**Comment by TimMoore** [comment]
Sure, thanks @lakhina!

**Comment by ignasi35** [comment]
This is obsolete since #42 was merged.
