### ISSUE TITLE
Document how to install sbt in readme.md

### ISSUE THREAD

**Issue by ignasi35** [lagom/online-auction-java#43]
Readme.md could contain a link on how to get `sbt` installed.

**Comment by ignasi35** [comment]
Alternatively we could add `sbt-launcher` on the repo using https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt but that required  cgywin on Windows and would require detailed instructions and extra installing for windows users anyway.

**Comment by lakhina** [comment]
@ignasi35 I tried `sbt-launche`r with both linux and cygwin and I felt that even though `sbt-launcher` is better option for linux systems but simple `sbt` installation is better in case of windows.

So I propose to put
- `sbt-launcher` in case of linux system
- `sbt` installation for both windows and linux

Should I update README accordingly?

**Comment by ignasi35** [comment]
Well, installing `sbt` is complex enough that sbt's documentation has a dedicated page for each platform ( [Mac](http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Mac.html), [Windows](http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Windows.html) and [Linux](http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Linux.html) ).

`activator` used to be included in the repo so that a user would only need to clone the repo to run the application. Given your experience with `sbt-launcher` I think linking to each page in the `sbt` documentation is reasonable at this time.

Thanks!
