### ISSUE TITLE
Run tests on multiple scala versions

### ISSUE THREAD

**Issue by ignasi35** [lagom/online-auction-java#62]
While working on PR #61  the main comand to run the tests `sbt +test` changed and the current command is not executing the tests cross-scala version: `sbt -DenableElasticsearch=true test` . 

This is probably what we want but I'd like to double check it was not added on purpose to demo a particular feature.

/cc @jroper

**Comment by TimMoore** [comment]
I don't know the context, but I'd guess it was probably picked up from the template and never really considered deliberately: https://github.com/lagom/activator-lagom-java/commit/d939cbbb372d8a29a0360c6ed42cd3b029131422
