### ISSUE TITLE
Reuse PaginatedSequence and move to a common project

### ISSUE THREAD

**Issue by yg-apaza** [lagom/online-auction-java#73]
```
./item-api/src/main/java/com/example/auction/item/api/PaginatedSequence.java:9:
// TODO: move to a common sbt project to reuse from searchApi
./search-api/src/main/java/com/example/auction/search/api/SearchResult.java:7:
// TODO: migrate to PaginatedSequence and reuse code. Needs moving PaginatedSequence to a shared project.
```
- Move PaginatedSequence.java (item-api) to com.example.auction.utils in security project (like in online-auction-scala)
- Migrate SearchResult to use PaginatedSequence

**Comment by yg-apaza** [comment]
@TimMoore @ignasi35 Is the description of this issue valid? Can I start working on it?

**Comment by TimMoore** [comment]
That sounds about right, but I'm not sure that it makes sense to call the common project "security", since `PaginatedSequence` has nothing to do with security. We may want to rename it to "common" in both versions, or alternatively we might want to go fine grained and have separate "security" and "pagination" projects. Any thoughts?

**Comment by TimMoore** [comment]
Also, it might not be totally clear, but I think "Migrate SearchResult to PaginatedSequence" really means "Migrate SearchResult to _use_ PaginatedSequence".

**Comment by ignasi35** [comment]
Extracting these common code should not alter the `security` project. We may want to reuse the `tools/` project (which is already shared with some services) but it should be clear that this code is not meant for Lagom core.

> I think "Migrate SearchResult to PaginatedSequence" really means "Migrate SearchResult to use PaginatedSequence".

@TimMoore 's suspicion is correct. I was on a hurry and "Migrate SearchResult to use PaginatedSequence" is what I really meant.

**Comment by yg-apaza** [comment]
Since `PaginatedSequence` and `SearchResult` have same fields, is this issue about replacing `SearchResult` with `PaginatedSequence<SearchItem>`?
Also, is it ok to move `PaginatedSequence` to `tools/` (com.example.auction.pagination)?

**Comment by ignasi35** [comment]
> Since PaginatedSequence and SearchResult have same fields, is this issue about replacing SearchResult with PaginatedSequence<SearchItem>?

Yes, we didn't do it at first because it wasn't clear that the final classes would be so alike.

>Also, is it ok to move PaginatedSequence to tools/ (com.example.auction.pagination)?

Yes.
