### ISSUE TITLE
Remove custom optional serializer

### ISSUE THREAD

**Issue by ignasi35** [lagom/online-auction-java#75]
#11 introduced a custom serializer for java Optional (see https://github.com/lagom/online-auction-java/blob/master/item-impl/src/main/resources/application.conf#L11-L19 and related class/es).

When this is provided by Akka the custom serializer should be removed and the provided by used instead.

**Comment by lakhina** [comment]
@ignasi35 Not sure if you are pointing toward these https://github.com/lagom/online-auction-java/blob/master/user-api/src/main/java/com/example/auction/user/api/User.java#L17

**Comment by ignasi35** [comment]
Hi @lakhina. This issue refers to the serialization engine behind the persistence layer.

Lagom uses two different serialization solutions: one for the service layer (API) and another one to exchange information between the nodes of the akka cluster (pubsub, akka-persistence, etc...).

This issue refers to the later.

Some back-story: 
 - Akka provided serializers for several well-known types in both scala and java. Unfortunately, `java.util.Optional` was not on that list originally. In order to implement a Lagom persistent entity where a `State` could be `Optional<MyBasketOrder>` (or `Optional<PItem>`) a serializer for java's `Optional` was required. While it was not provided in Akka itself we developed our own for the online-auction app. Currently akka provides one so we should remove our custom serializer and let akka's pick up.

**Comment by lakhina** [comment]
@ignasi35 From my understanding at this point we have to replace usage of `com.lightbend.lagom.serialization` with usage of serialization from akka.
Am I going wrong?

**Comment by ignasi35** [comment]
@lakhina we have to make sure `[JOptionalSerializer](https://github.com/lagom/online-auction-java/blob/b6bea26afad45461a43c437dfd8ea70e52d783a4/item-impl/src/main/java/com/example/serializer/JOptionalSerializer.java)` (and related code) is removed but the application still works. ;-)
