### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by brw31415** [lagom/online-auction-java#83]
I cloned this (as sbt project) into IntelliJ, Java 8, and got the following:

Information:5/1/2017 8:11 PM - Compilation completed with 12 errors and 0 warnings in 2m 1s 500ms
C:\Users\RLOPACs\online-auction-java\tools\src\main\java\com\example\auction\pagination\PaginatedSequence.java
Error:(3, 14) java: package lombok does not exist
Error:(4, 24) java: package org.pcollections does not exist

Error:(9, 2) java: cannot find symbol
  symbol: class Value

Error:(11, 5) java: cannot find symbol
  symbol:   class PSequence
  location: class com.example.auction.pagination.PaginatedSequence<T>

Error:(16, 30) java: cannot find symbol
  symbol:   class PSequence
  location: class com.example.auction.pagination.PaginatedSequence<T>

Error:(3, 12) java: package akka does not exist

Error:(24, 35) java: cannot find symbol
  symbol:   class Done
  location: class com.example.core.CompletionStageUtils

Error:(35, 39) java: cannot find symbol
  symbol:   class Done
  location: class com.example.core.CompletionStageUtils

Error:(36, 74) java: cannot find symbol
  symbol:   variable Done
  location: class com.example.core.CompletionStageUtils

Error:(36, 74) java: cannot find symbol
  symbol:   variable Done
  location: class com.example.core.CompletionStageUtils

**Comment by TimMoore** [comment]
Hi @brw31415 have you followed the IDE setup guides?

* [Importing an sbt project into IntelliJ](https://www.lagomframework.com/documentation/1.3.x/java/IntellijSbtJava.html)
* [Integrating Lombok with an IDE](https://www.lagomframework.com/documentation/1.3.x/java/Immutable.html#Integrating-Lombok-with-an-IDE)

**Comment by lakhina** [comment]
@TimMoore Should we close this issue?

**Comment by ignasi35** [comment]
HI @brw31415 I assume this was fixed on your environment so I'll close the issue. Feel free to report back and reopen again if other problems related to this issue arise.
