### ISSUE TITLE
Update readme: link to getting started pages

### ISSUE THREAD

**Issue by ignasi35** [lagom/online-auction-java#85]
Current readme links to documentation introducing hello world. It'd be better if the links pointed to "https://www.lagomframework.com/get-started-java-maven.html" (and sbt equivalent) instead of "https://www.lagomframework.com/documentation/1.3.x/java/GettingStartedMaven.html"

**Comment by lakhina** [comment]
@ignasi35 Lemme do it

**Comment by ignasi35** [comment]
Please, be my guest. :-)

**Comment by lakhina** [comment]
@ignasi35 I have updated the links.Please review

**Comment by ignasi35** [comment]
Yay!
