### ISSUE TITLE
Ensure all value classes implement equals/hashCode/toString

### ISSUE THREAD

**Issue by TimMoore** [lagom/online-auction-java#9]
See https://github.com/lagom/online-auction-java/pull/6#discussion_r86748638

**Comment by lakhina** [comment]
@TimMoore I see PR is merged about this issue. This issue is still open?

**Comment by TimMoore** [comment]
@lakhina the PR referenced above is the original pull request where this issue was pointed out in the first place. It doesn't fix this problem.

**Comment by lakhina** [comment]
@TimMoore Ok I will look into it

**Comment by yg-apaza** [comment]
So, we need to ensure that all classes use lombok Value?

**Comment by ignasi35** [comment]
@lakhina & @yg-apaza there's many ways to fix this issue, one of them is to make all classes use Lombok, another one is to review the current implementation adding/recreating equals/hashCode/toString for all value classes.

Each option has advantages and inconvenients.
